exports.hrQuestions = [
  "Tell me about yourself.",
  "Why are you interested in this position?",
  "What do you know about our company?",
  "Can you describe a challenging situation at work and how you handled it?",
  "What are your strengths and weaknesses?",
  "Where do you see yourself in five years?",
  "How do you handle tight deadlines and pressure?",
  "Can you provide an example of a successful project you worked on?",
  "How do you prioritize your tasks when working on multiple projects?",
  "What motivates you to do your best at work?",
  "How do you handle feedback and criticism?",
  "Describe your ideal work environment.",
  "Can you tell me about a time you demonstrated leadership skills?",
  "How do you approach professional development and learning new skills?",
  "How do you handle conflicts with coworkers?",
  "Can you describe a time when you had to go above and beyond your job responsibilities?",
  "How do you manage work-life balance?",
  "What do you enjoy most about working in software development?",
  "How do you stay organized and manage your time effectively?",
  "What do you think makes a successful team?",
];

exports.technicalQuestions = [
  "How do you configure routing in an Angular application?",
  "Can you explain Angular's dependency injection system?",
  "What is the difference between Angular's template-driven and reactive forms?",
  "How do you handle authentication and authorization in an Angular application?",
  "Can you describe the process of creating a custom Angular directive?",
  "How do you integrate Angular with a RESTful API?",
  "What are Angular services, and how do you use them?",
  "How do you manage state in an Angular application using NgRx?",
  "Can you explain Angular's module system and the purpose of NgModule?",
  "How do you handle error handling and logging in an Angular application?",
  "What are the main features of Spring Boot, and why would you use it?",
  "Can you explain the concept of dependency injection in Spring Boot?",
  "How do you create a RESTful API with Spring Boot?",
  "What is Spring Boot's auto-configuration, and how does it work?",
  "How do you handle database connections and transactions in Spring Boot?",
  "Can you explain the purpose of Spring Boot's `application.properties` file?",
  "How do you create and manage entities in Spring Data JPA with Kotlin?",
  "What are Kotlin coroutines, and how do you use them in a Spring Boot application?",
  "How do you handle exception handling in Spring Boot?",
  "Can you explain the purpose of Spring Security, and how do you implement it in a Spring Boot application?",
  "How do you design and implement a full-stack application using Angular and Spring Boot?",
  "Can you explain how to secure communication between an Angular frontend and a Spring Boot backend?",
  "How do you handle data transfer between Angular and Spring Boot using DTOs?",
  "What strategies do you use for error handling in a full-stack application with Angular and Spring Boot?",
  "How do you implement authentication and authorization across Angular and Spring Boot?",
  "Can you describe the process of setting up a CI/CD pipeline for an Angular and Spring Boot application?",
  "How do you manage and deploy configurations for both Angular and Spring Boot applications?",
  "How do you optimize performance for a full-stack application using Angular and Spring Boot?",
  "Can you explain how to test a full-stack application with Angular as the frontend and Spring Boot as the backend?",
  "How do you handle asynchronous operations and data streaming between Angular and a Spring Boot backend using Kotlin?",
  "Can you explain the main concepts of Angular?",
  "What is data binding in Angular, and what are its types?",
  "How do you create and inject a service in Angular?",
  "What is the purpose of NgModule in Angular?",
  "How does Angular handle forms, and what is the difference between template-driven and reactive forms?",
  "Can you explain Angular's change detection mechanism?",
  "What are Angular directives, and can you name a few built-in directives?",
  "How do you implement routing in an Angular application?",
  "What is RxJS, and how is it used in Angular?",
  "How do you manage state in an Angular application?",
  "Can you explain what Angular CLI is and how it is used?",
  "What is lazy loading in Angular, and why is it beneficial?",
  "How do you handle error handling in Angular applications?",
  "What are Angular pipes, and how do you create a custom pipe?",
  "Can you explain the concept of dependency injection in Angular?",
  "What are Angular lifecycle hooks, and can you name a few?",
  "How do you optimize the performance of an Angular application?",
  "What is the difference between Angular and AngularJS?",
  "How do you handle forms and validations in Angular?",
  "Can you explain the purpose and use of Angular's HttpClient module?",
];

exports.followUpQuestions = [
  "How do you keep yourself updated with the latest developments in Angular and web development in general?",
  "Can you walk me through a recent Angular project you worked on, explaining your role and the technologies you used?",
  "How do you approach debugging and troubleshooting in Angular?",
  "What strategies do you use to ensure your code is maintainable and scalable?",
  "Can you describe a situation where you had to work with a difficult team member and how you resolved it?",
  "How do you approach testing in Angular, including unit testing and end-to-end testing?",
  "Can you describe your experience with state management libraries such as NgRx or Akita?",
  "How do you handle asynchronous operations in Angular?",
  "What are the security best practices you follow when developing Angular applications?",
  "Can you explain the difference between components and services in Angular?",
  "How do you integrate third-party libraries into an Angular project?",
  "What is Angular Universal, and how is it used?",
  "Can you discuss a time when you had to refactor an Angular application for better performance or maintainability?",
  "How do you ensure cross-browser compatibility in your Angular applications?",
  "Can you describe a challenging bug you encountered in an Angular project and how you resolved it?",
];
